version: "3"
services: 
  api:
    build: ./
    image: dalongrong/openresty:lua-resty-repl
    volumes:
    - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    - "./supervisor.conf:/etc/supervisor.conf"
    ports:
    - "80:80"
    - "9001:9001"